### ISSUE TITLE
[Feature Suggest] Mimicking Slow Internet Loads

### ISSUE THREAD

**Issue by MaximumSuperlative** [input-variable/neversaygoodbye#5]
Have navigating between webpages occasionally result in a "slow internet" situation where the page loads in stuttered blocks as opposed to instantly.

**Comment by kevroded** [comment]
Working on implementing it in my fork. Will submit a pull request when done

**Comment by input-variable** [comment]
Merged pull request ea88164eafc11b651f17203e260caad2bd3e4035
