### ISSUE TITLE
[Issue] Notification bubble clipping

### ISSUE THREAD

**Issue by MaximumSuperlative** [input-variable/neversaygoodbye#7]
Clicking on the notification pop-up makes the resulting menu clip out the top part of the red bubble instead of making the red bubble disappear altogether. The overlap from the other bottom bar pop-ups is fine.
![image_2021-04-24_212028](https://user-images.githubusercontent.com/83033525/115971863-e39bdf80-a542-11eb-9e0f-17121e54abfc.png)

**Comment by input-variable** [comment]
Will resolve this in the next pull request.

**Comment by input-variable** [comment]
Resolved with commit 9ff3a80. Thanks for bringing this up.
